language: java

jdk:
  - oraclejdk8

before_install:
  - curl -s get.sdkman.io > ~/install_sdkman.sh
  - chmod 775 ~/install_sdkman.sh
  - ~/install_sdkman.sh
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - sdk install springboot 1.3.0.RELEASE

script: test/run.sh
